// <auto-generated />
using BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Data.Migrations
{
    [DbContext(typeof(GeographicalDataContext))]
    [Migration("20250717152902_SqlServerMigration")]
    partial class SqlServerMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Domain.Entities.GeographicalDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gemeente");

                    b.Property<string>("Huisletter")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("huisletter");

                    b.Property<int>("Huisnummer")
                        .HasColumnType("int")
                        .HasColumnName("huisnummer");

                    b.Property<int?>("Huisnummertoevoeging")
                        .HasColumnType("int")
                        .HasColumnName("huisnummertoevoeging");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("lat");

                    b.Property<decimal>("Lon")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("lon");

                    b.Property<string>("Nevenadres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nevenadres");

                    b.Property<string>("Nummeraanduiding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nummeraanduiding");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("objectid");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("objecttype");

                    b.Property<string>("Openbareruimte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("openbareruimte");

                    b.Property<int>("Oppervlakteverblijfsobject")
                        .HasColumnType("int")
                        .HasColumnName("oppervlakteverblijfsobject");

                    b.Property<int>("Pandbouwjaar")
                        .HasColumnType("int")
                        .HasColumnName("pandbouwjaar");

                    b.Property<string>("Pandid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pandid");

                    b.Property<string>("Pandstatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pandstatus");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("postcode");

                    b.Property<string>("Provincie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provincie");

                    b.Property<string>("Verblijfsobjectgebruiksdoel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("verblijfsobjectgebruiksdoel");

                    b.Property<string>("Verblijfsobjectstatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("verblijfsobjectstatus");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("woonplaats");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("Gemeente")
                        .HasDatabaseName("IX_GeographicalData_Gemeente");

                    b.HasIndex("Postcode")
                        .HasDatabaseName("IX_GeographicalData_Postcode");

                    b.HasIndex("Woonplaats")
                        .HasDatabaseName("IX_GeographicalData_Woonplaats");

                    b.HasIndex("Openbareruimte", "Huisnummer", "Postcode")
                        .HasDatabaseName("IX_GeographicalData_Address");

                    b.ToTable("GeographicalData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gemeente = "Amsterdam",
                            Huisnummer = 1,
                            Lat = 52.370216m,
                            Lon = 4.895168m,
                            Nummeraanduiding = "1",
                            ObjectId = "OBJ1",
                            ObjectType = "Pand",
                            Openbareruimte = "Hoofdstraat",
                            Oppervlakteverblijfsobject = 100,
                            Pandbouwjaar = 1990,
                            Pandid = "PAND1",
                            Pandstatus = "Bestaand",
                            Postcode = "1234AB",
                            Provincie = "Noord-Holland",
                            Verblijfsobjectgebruiksdoel = "Wonen",
                            Verblijfsobjectstatus = "Actief",
                            Woonplaats = "Amsterdam",
                            X = 12345,
                            Y = 67890
                        },
                        new
                        {
                            Id = 2,
                            Gemeente = "Rotterdam",
                            Huisletter = "A",
                            Huisnummer = 2,
                            Lat = 51.9225m,
                            Lon = 4.47917m,
                            Nummeraanduiding = "2A",
                            ObjectId = "OBJ2",
                            ObjectType = "Pand",
                            Openbareruimte = "Dorpsstraat",
                            Oppervlakteverblijfsobject = 80,
                            Pandbouwjaar = 1980,
                            Pandid = "PAND2",
                            Pandstatus = "Bestaand",
                            Postcode = "5678CD",
                            Provincie = "Zuid-Holland",
                            Verblijfsobjectgebruiksdoel = "Wonen",
                            Verblijfsobjectstatus = "Actief",
                            Woonplaats = "Rotterdam",
                            X = 54321,
                            Y = 98765
                        },
                        new
                        {
                            Id = 3,
                            Gemeente = "Utrecht",
                            Huisnummer = 3,
                            Huisnummertoevoeging = 1,
                            Lat = 52.09074m,
                            Lon = 5.12142m,
                            Nummeraanduiding = "3-1",
                            ObjectId = "OBJ3",
                            ObjectType = "Pand",
                            Openbareruimte = "Kerkstraat",
                            Oppervlakteverblijfsobject = 120,
                            Pandbouwjaar = 2000,
                            Pandid = "PAND3",
                            Pandstatus = "Bestaand",
                            Postcode = "9012EF",
                            Provincie = "Utrecht",
                            Verblijfsobjectgebruiksdoel = "Wonen",
                            Verblijfsobjectstatus = "Actief",
                            Woonplaats = "Utrecht",
                            X = 11111,
                            Y = 22222
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
