// <auto-generated />
using BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Data.Migrations
{
    [DbContext(typeof(GeographicalDataContext))]
    partial class GeographicalDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BE.Domain.Models.GeographicalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Huisletter")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("Huisnummer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Huisnummertoevoeging")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("decimal(18,6)");

                    b.Property<double>("Lon")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Nevenadres")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nummeraanduiding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Openbareruimte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Oppervlakteverblijfsobject")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pandbouwjaar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pandid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pandstatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Verblijfsobjectgebruiksdoel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Verblijfsobjectstatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Gemeente")
                        .HasDatabaseName("IX_GeographicalData_Gemeente");

                    b.HasIndex("Postcode")
                        .HasDatabaseName("IX_GeographicalData_Postcode");

                    b.HasIndex("Woonplaats")
                        .HasDatabaseName("IX_GeographicalData_Woonplaats");

                    b.HasIndex("Openbareruimte", "Huisnummer", "Postcode")
                        .HasDatabaseName("IX_GeographicalData_Address");

                    b.ToTable("GeographicalData");
                });
#pragma warning restore 612, 618
        }
    }
}
