// <auto-generated />
using System;
using BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(GeographicalDataContext))]
    partial class GeographicalDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BE.Models.GeographicalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Huisletter")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("Huisnummer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Huisnummertoevoeging")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("decimal(18,6)");

                    b.Property<double>("Lon")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Nevenadres")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nummeraanduiding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Openbareruimte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Oppervlakteverblijfsobject")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pandbouwjaar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pandid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pandstatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Verblijfsobjectgebruiksdoel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Verblijfsobjectstatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Gemeente")
                        .HasDatabaseName("IX_GeographicalData_Gemeente");

                    b.HasIndex("Postcode")
                        .HasDatabaseName("IX_GeographicalData_Postcode");

                    b.HasIndex("Woonplaats")
                        .HasDatabaseName("IX_GeographicalData_Woonplaats");

                    b.HasIndex("Openbareruimte", "Huisnummer", "Postcode")
                        .HasDatabaseName("IX_GeographicalData_Address");

                    b.ToTable("GeographicalData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gemeente = "Amsterdam",
                            Huisletter = "A",
                            Huisnummer = 1,
                            Lat = 52.367600000000003,
                            Lon = 4.9040999999999997,
                            Nummeraanduiding = "0363010000000001",
                            ObjectId = "NL.IMBAG.Verblijfsobject.0363010000000001",
                            ObjectType = "Verblijfsobject",
                            Openbareruimte = "Kerkstraat",
                            Oppervlakteverblijfsobject = 75,
                            Pandbouwjaar = 1950,
                            Pandid = "NL.IMBAG.Pand.0363100000000001",
                            Pandstatus = "Pand in gebruik",
                            Postcode = "1234AB",
                            Provincie = "Noord-Holland",
                            Verblijfsobjectgebruiksdoel = "woonfunctie",
                            Verblijfsobjectstatus = "Verblijfsobject in gebruik",
                            Woonplaats = "Amsterdam",
                            X = 121000,
                            Y = 487000
                        },
                        new
                        {
                            Id = 2,
                            Gemeente = "Utrecht",
                            Huisnummer = 25,
                            Lat = 52.090699999999998,
                            Lon = 5.1214000000000004,
                            Nummeraanduiding = "0344010000000002",
                            ObjectId = "NL.IMBAG.Verblijfsobject.0344010000000002",
                            ObjectType = "Verblijfsobject",
                            Openbareruimte = "Hoofdstraat",
                            Oppervlakteverblijfsobject = 120,
                            Pandbouwjaar = 1975,
                            Pandid = "NL.IMBAG.Pand.0344100000000002",
                            Pandstatus = "Pand in gebruik",
                            Postcode = "3511AB",
                            Provincie = "Utrecht",
                            Verblijfsobjectgebruiksdoel = "winkelfunctie",
                            Verblijfsobjectstatus = "Verblijfsobject in gebruik",
                            Woonplaats = "Utrecht",
                            X = 155000,
                            Y = 463000
                        },
                        new
                        {
                            Id = 3,
                            Gemeente = "Nijmegen",
                            Huisletter = "B",
                            Huisnummer = 8,
                            Huisnummertoevoeging = 2,
                            Lat = 51.812600000000003,
                            Lon = 5.8520000000000003,
                            Nummeraanduiding = "0268010000000003",
                            ObjectId = "NL.IMBAG.Verblijfsobject.0268010000000003",
                            ObjectType = "Verblijfsobject",
                            Openbareruimte = "Dorpsplein",
                            Oppervlakteverblijfsobject = 200,
                            Pandbouwjaar = 2000,
                            Pandid = "NL.IMBAG.Pand.0268100000000003",
                            Pandstatus = "Pand in gebruik",
                            Postcode = "6543CD",
                            Provincie = "Gelderland",
                            Verblijfsobjectgebruiksdoel = "kantoorfunctie",
                            Verblijfsobjectstatus = "Verblijfsobject in gebruik",
                            Woonplaats = "Nijmegen",
                            X = 190000,
                            Y = 426000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
